local M = {}

M.highlights_base = function(colors)
  return {

    -- Editor elements
    NonText = { ctermfg = 0 },
    Ignore = { ctermfg = "None", ctermbg = "None", cterm = "None" },
    Bold = { cterm = "bold" },
    Italic = { cterm = "italic" },
    StatusLine = { ctermfg = 15, ctermbg = 8, cterm = "None" },
    StatusLineNC = { ctermfg = 15, ctermbg = 0, cterm = "None" },
    VertSplit = { ctermfg = 8 },
    TabLine = { ctermfg = 7, ctermbg = 0 },
    TabLineFill = { ctermfg = 0, ctermbg = 0 },
    TabLineSel = { ctermfg = 0, ctermbg = 11 },
    Title = { ctermfg = 4, cterm = "bold" },
    CursorLine = { ctermbg = 0, ctermfg = "None" },
    Cursor = { ctermbg = 15, ctermfg = 0 },
    CursorColumn = { ctermbg = 0 },
    LineNr = { ctermfg = 8 },
    CursorLineNr = { ctermfg = 6 },
    helpLeadBlank = { ctermbg = "None", ctermfg = "None" },
    helpNormal = { ctermbg = "None", ctermfg = "None" },
    Visual = { ctermbg = 8, ctermfg = 15, cterm = "bold" },
    VisualNos = { ctermbg = 8, ctermfg = 15, cterm = "bold" },
    Pmenu = { ctermbg = 0, ctermfg = 15 },
    PmenuSbar = { ctermbg = 8, ctermfg = 7 },
    PmenuSel = { ctermbg = 8, ctermfg = 15, cterm = "bold" },
    PmenuThumb = { ctermbg = 7, ctermfg = "None" },
    FoldColumn = { ctermfg = 7 },
    Folded = { ctermfg = 12 },
    WildMenu = { ctermbg = 0, ctermfg = 15, cterm = "None" },
    SpecialKey = { ctermfg = 0 },
    IncSearch = { ctermfg = 1, ctermbg = 0 },
    CurSearch = { ctermbg = 3, ctermfg = 0 },
    Search = { ctermbg = 11, ctermfg = 0 },
    Directory = { ctermfg = 4 },
    MatchParen = { ctermfg = 3, ctermbg = 0, cterm = "underline" },
    SpellBad = { cterm = "undercurl" },
    SpellCap = { cterm = "undercurl" },
    SpellLocal = { cterm = "undercurl" },
    SpellRare = { cterm = "undercurl" },
    ColorColumn = { ctermbg = 8 },
    SignColumn = { ctermfg = 7 },
    ModeMsg = { ctermfg = 0, ctermbg = 15, ctermb = "bold" },
    MoreMsg = { ctermfg = 4 },
    Question = { ctermfg = 4 },
    QuickFixLine = { ctermfg = 14, ctermbg = 0 },
    Conceal = { ctermfg = 8 },
    ToolbarLine = { ctermfg = 15, ctermbg = 0 },
    ToolbarButton = { ctermfg = 15, ctermbg = 8 },
    debugPC = { ctermfg = 7 },
    debugBreakpoint = { ctermfg = 8 },
    ErrorMsg = { ctermfg = 1, cterm = "bold, italic" },
    WarningMsg = { ctermfg = 11 },
    DiffAdd = { ctermfg = 0, ctermbg = 10 },
    DiffChange = { ctermfg = 0, ctermbg = 12 },
    DiffDelete = { ctermfg = 0, ctermbg = 9 },
    Difftext = { ctermfg = 0, ctermbg = 14 },
    diffAdded = { ctermfg = 10 },
    diffRemoved = { ctermfg = 9 },
    diffChanged = { ctermfg = 12 },
    diffOldFile = { ctermfg = 11 },
    diffNewFile = { ctermfg = 13 },
    diffFile = { ctermfg = 12 },
    diffLine = { ctermfg = 7 },
    diffIndexLine = { ctermfg = 14 },
    healthError = { ctermfg = 1 },
    healthSuccess = { ctermfg = 2 },
    healthWarning = { ctermfg = 3 },

    --Syntax
    Comment = { ctermfg = 8, cterm = "italic" },
    Constant = { ctermfg = 3 },
    Error = { ctermfg = 1 },
    Identifier = { ctermfg = 9 },
    Function = { ctermfg = 4 },
    Special = { ctermfg = 13 },
    Statement = { ctermfg = 5 },
    String = { ctermfg = 2 },
    Operator = { ctermfg = 6 },
    Boolean = { ctermfg = 3 },
    Label = { ctermfg = 14 },
    Keyword = { ctermfg = 5 },
    Expection = { ctermfg = 5},
    Conditional = {ctermfg = 5},
    PreProc = { ctermfg = 13},
    Include = {ctermfg = 5},
    Macro = { ctermfg = 5},
    StorageClass = {ctermfg = 11},
    Structure = { ctemrfg = 11},
    Todo = {ctermfg = 0, ctermbg = 9, ctermb = "bold"},
    Type = {ctermfg = 11},

    NormalFloat = {ctermfg = 15, ctermbg = 0},
    FloatBoarder = {ctermfg = 7, ctermbg = 0},
    FloatShadow = {ctermfg = 15, ctermbg = 0},
  }
end

return M
